# /group_vars/all.yaml
### Variable Parameter ###
## CentOS Repo
repo_url_centos: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
repo_gpg_centos: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
repo_docker_centos: "https://download.docker.com/linux/centos/docker-ce.repo"

## Ubuntu Repo
repo_url_ubuntu: "https://apt.kubernetes.io/ kubernetes-xenial main"
repo_gpg_ubuntu: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

#kubernetes
pod_network: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
path_k8s: $HOME/.kube

#kubeedge
path_kubeedge: $HOME/kubeedge
kubeedge_git_pc: "https://github.com/kubeedge/kubeedge/releases/download/v1.7.1/keadm-v1.7.1-linux-amd64.tar.gz"
kubeedge_git_arm: "https://github.com/kubeedge/kubeedge/releases/download/v1.7.1/keadm-v1.7.1-linux-arm.tar.gz"
kubeedge_git_arm64: "https://github.com/kubeedge/kubeedge/releases/download/v1.7.1/keadm-v1.7.1-linux-arm64.tar.gz"