# /roles/kube_dependecies/tasks/dependencies.yml
---
# Set dependencies
- name: Add kubernetes apt-key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubernetes repo
  ansible.builtin.apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: "kubernetes"

- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: present
  loop:
    - name: apt-transport-https
    - name: curl
    - name: docker.io

- name: Install only on primary node
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: present
  loop:
    - name: kubeadm
    - name: kubelet
    - name: kubectl
  when: ansible_default_ipv4.address == hostvars['primary1'].ansible_host

# Notice:
# Whole group {{ hostvars['host_group'].ansible_host }}
# First entry of group {{ hostvars[groups['host_group'][0]].ansible_host }}

- name: Create KubeEdge folder in home
  ansible.builtin.file:
    path: "{{ path_kubeedge }}"
    state: directory

- name: Download KubeEdge from Git pc
  ansible.builtin.get_url:
    dest: "{{ path_kubeedge }}"
    url: "{{ kubeedge_git_pc }}"
  when: "'pcgroup' in group_names"

- name: Download KubeEdge from Git arm
  ansible.builtin.get_url:
    dest: "{{ path_kubeedge }}"
    url: "{{ kubeedge_git_arm }}"
  when: "'nodesARM' in group_names"

- name: Download KubeEdge from Git arm64
  ansible.builtin.get_url:
    dest: "{{ path_kubeedge }}"
    url: "{{ kubeedge_git_arm64 }}"
  when: "'nodesARM64' in group_names"

- name: Find KubeEdge zip
  ansible.builtin.find:
    paths: "{{ path_kubeedge }}"
    patterns: "keadm-v1.7.1-linux-*.tar.gz"
  register: find_result

- name: Unarchive a file
  ansible.builtin.unarchive:
    src: "{{ find_result['files'][0]['path'] }}" 
    dest: "{{ path_kubeedge }}"
    remote_src: yes
...
