# /roles/kube_dependecies/tasks/dependencies_rhel.yml
---
# Set dependencies
- name: Add kubernetes repo CentOS
  ansible.builtin.yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    baseurl: "{{ repo_url_centos }}"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "{{ repo_gpg_centos }}"
  when: "ansible_default_ipv4.address == hostvars['primary1'].ansible_host"

- name: Add docker repo CentOS
  ansible.builtin.command:
    cmd: "dnf config-manager --add-repo={{ repo_docker_centos }}"

- name: Update cache CentOS
  ansible.builtin.dnf:
    update_cache: yes

- name: Install dependencies on CentOS
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: present
  loop:
    - name: curl
    - name: wget
    - name: ca-certificates
    - name: docker-ce 
    - name: docker-ce-cli 
    - name: containerd.io

- name: Install only on primary node CentOS
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: present
  loop:
    - name: kubeadm
    - name: kubelet
    - name: kubectl
  when: ansible_default_ipv4.address == hostvars['primary1'].ansible_host
...