# /roles/kube_dependecies/tasks/dependencies_ubuntu.yml
---
# Set dependencies
- name: Add kubernetes apt-key
  ansible.builtin.apt_key:
    url: "{{ repo_gpg_ubuntu }}"
    state: present
  when: "ansible_default_ipv4.address == hostvars['primary1'].ansible_host"

- name: Add kubernetes repo ubuntu
  ansible.builtin.apt_repository:
    repo: "deb {{ repo_url_ubuntu }}" 
    state: present
    filename: "kubernetes"
  when: "ansible_default_ipv4.address == hostvars['primary1'].ansible_host"

- name: Update cache ubuntu
  ansible.builtin.apt:
    update_cache: true

- name: Install dependencies ubuntu
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - curl
      - wget
      - ca-certificates
      - docker.io
    state: present
    
- name: Install only on primary node ubuntu
  ansible.builtin.apt:
    pkg: 
      - kubeadm
      - kubelet
      - kubectl
    state: present
  when: ansible_default_ipv4.address == hostvars['primary1'].ansible_host
...