# /roles/kube_dependecies/tasks/dependencies.yml
---
# Turn SWAP off
- name: Turn swap off
  ansible.builtin.shell: swapoff -a

- name: Disable SWAP in fstab
  ansible.builtin.replace:
    path: "/etc/fstab"
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
...