# /roles/kube_dependecies/tasks/dependencies.yml
---
# Turn SWAP off
- name: Turn swap off
  shell: swapoff -a

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
...
