# /site.yml
---
- name: Main YML for Kubernetes and KubeEdge cluster dependencies
  hosts: kubernetes
  become: yes
  roles:
    - name: Kubernetes and KubeEdge dependencies
      role: kube_dependencies

- name: Configure cluster primary
  hosts: primary
  become: yes
  roles:
    - name: Cluster primary
      role: kube_primary

- name: Configure cluster nodes
  hosts: nodes
  become: yes
  roles:
    - name: Cluster node
      role: kube_node
...
