# /roles/kube_primary/tasks/install_cluster_primary.yml
---
# Prerequesits
- name: Create .kube directory
  ansible.builtin.file:
    path: "{{ path_k8s }}"
    state: directory
    mode: 0755

# Configure kubernetes primary
- name: Initialize the cluster
  ansible.builtin.shell: "kubeadm init  --apiserver-advertise-address={{ hostvars[inventory_hostname].ansible_host }} --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt"
  args:
    chdir: "{{ path_k8s }}" 
    creates: cluster_initialized.txt

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ path_k8s }}/config"
    remote_src: yes
    owner: root

# Set pod Network
- name: Install Pod network
  ansible.builtin.shell: kubectl apply -f "{{ pod_network }}" >> pod_network_setup.txt
  args:
    chdir: "{{ path_k8s }}"
    creates: pod_network_setup.txt

# Kubernetes join token
- name: Get kubernetes join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_k8s_command_raw

- name: Set kubernetes join command
  ansible.builtin.set_fact:
    join_k8s_command: "{{ join_k8s_command_raw.stdout_lines[0] }}"
...