# /roles/kube_node/tasks/install_cluster_node.yml
---
# Configure kubeedge nodes
- name: Join kubeedge cloud side
  ansible.builtin.shell: "{{ path_kubeedge }}/keadm-v1.7.1-linux-amd64/keadm/keadm join --cloudcore-ipport={{ hostvars['primary1'].ansible_host }}:10000 --token={{ hostvars['primary1'].join_kubeedge_command }}"
...
